name: Tests

on: [push]

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 'configMapGenerator:
              - name: example
                literals:
                  - FOO=Bar' > kustomization.yaml
      - uses: ./
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: version
